package com.fnic.mybatis.thingsboard.dao;

import com.fnic.mybatis.thingsboard.model.AdminSettings;
import com.fnic.mybatis.thingsboard.model.AdminSettingsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AdminSettingsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_settings
     *
     * @mbg.generated
     */
    long countByExample(AdminSettingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_settings
     *
     * @mbg.generated
     */
    int deleteByExample(AdminSettingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_settings
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_settings
     *
     * @mbg.generated
     */
    int insert(AdminSettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_settings
     *
     * @mbg.generated
     */
    int insertSelective(AdminSettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_settings
     *
     * @mbg.generated
     */
    List<AdminSettings> selectByExample(AdminSettingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_settings
     *
     * @mbg.generated
     */
    AdminSettings selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_settings
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AdminSettings record, @Param("example") AdminSettingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_settings
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AdminSettings record, @Param("example") AdminSettingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_settings
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AdminSettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_settings
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdminSettings record);
}