package com.fnic.mybatis.thingsboard.dao;

import com.fnic.mybatis.thingsboard.model.Alarm;
import com.fnic.mybatis.thingsboard.model.AlarmExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AlarmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    long countByExample(AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    int deleteByExample(AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    int insert(Alarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    int insertSelective(Alarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    List<Alarm> selectByExample(AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    Alarm selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Alarm record, @Param("example") AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Alarm record, @Param("example") AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Alarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Alarm record);
}