package com.fnic.mybatis.thingsboard.dao;

import com.fnic.mybatis.thingsboard.model.Dashboard;
import com.fnic.mybatis.thingsboard.model.DashboardExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DashboardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard
     *
     * @mbg.generated
     */
    long countByExample(DashboardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard
     *
     * @mbg.generated
     */
    int deleteByExample(DashboardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard
     *
     * @mbg.generated
     */
    int insert(Dashboard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard
     *
     * @mbg.generated
     */
    int insertSelective(Dashboard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard
     *
     * @mbg.generated
     */
    List<Dashboard> selectByExample(DashboardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard
     *
     * @mbg.generated
     */
    Dashboard selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Dashboard record, @Param("example") DashboardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Dashboard record, @Param("example") DashboardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Dashboard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dashboard
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dashboard record);
}