package com.fnic.mybatis.thingsboard.dao;

import com.fnic.mybatis.thingsboard.model.DeviceCredentials;
import com.fnic.mybatis.thingsboard.model.DeviceCredentialsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DeviceCredentialsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_credentials
     *
     * @mbg.generated
     */
    long countByExample(DeviceCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_credentials
     *
     * @mbg.generated
     */
    int deleteByExample(DeviceCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_credentials
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_credentials
     *
     * @mbg.generated
     */
    int insert(DeviceCredentials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_credentials
     *
     * @mbg.generated
     */
    int insertSelective(DeviceCredentials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_credentials
     *
     * @mbg.generated
     */
    List<DeviceCredentials> selectByExample(DeviceCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_credentials
     *
     * @mbg.generated
     */
    DeviceCredentials selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_credentials
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DeviceCredentials record, @Param("example") DeviceCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_credentials
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DeviceCredentials record, @Param("example") DeviceCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_credentials
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DeviceCredentials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_credentials
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DeviceCredentials record);
}