package com.fnic.mybatis.thingsboard.dao;

import com.fnic.mybatis.thingsboard.model.Relation;
import com.fnic.mybatis.thingsboard.model.RelationExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    long countByExample(RelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    int deleteByExample(RelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    int insert(Relation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    int insertSelective(Relation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    List<Relation> selectByExample(RelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Relation record, @Param("example") RelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Relation record, @Param("example") RelationExample example);
}