package com.fnic.mybatis.thingsboard.dao;

import com.fnic.mybatis.thingsboard.model.Tenant;
import com.fnic.mybatis.thingsboard.model.TenantExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TenantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant
     *
     * @mbg.generated
     */
    long countByExample(TenantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant
     *
     * @mbg.generated
     */
    int deleteByExample(TenantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant
     *
     * @mbg.generated
     */
    int insert(Tenant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant
     *
     * @mbg.generated
     */
    int insertSelective(Tenant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant
     *
     * @mbg.generated
     */
    List<Tenant> selectByExample(TenantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant
     *
     * @mbg.generated
     */
    Tenant selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Tenant record, @Param("example") TenantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Tenant record, @Param("example") TenantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Tenant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Tenant record);
}