package com.fnic.mybatis.thingsboard.dao;

import com.fnic.mybatis.thingsboard.model.TsKv;
import com.fnic.mybatis.thingsboard.model.TsKvExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TsKvMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_kv
     *
     * @mbg.generated
     */
    long countByExample(TsKvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_kv
     *
     * @mbg.generated
     */
    int deleteByExample(TsKvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_kv
     *
     * @mbg.generated
     */
    int insert(TsKv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_kv
     *
     * @mbg.generated
     */
    int insertSelective(TsKv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_kv
     *
     * @mbg.generated
     */
    List<TsKv> selectByExample(TsKvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_kv
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TsKv record, @Param("example") TsKvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_kv
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TsKv record, @Param("example") TsKvExample example);
}