package com.fnic.mybatis.thingsboard.model;

public class AdminSettings {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_settings.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_settings.json_value
     *
     * @mbg.generated
     */
    private String jsonValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_settings.key
     *
     * @mbg.generated
     */
    private String key;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_settings.id
     *
     * @return the value of admin_settings.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_settings.id
     *
     * @param id the value for admin_settings.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_settings.json_value
     *
     * @return the value of admin_settings.json_value
     *
     * @mbg.generated
     */
    public String getJsonValue() {
        return jsonValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_settings.json_value
     *
     * @param jsonValue the value for admin_settings.json_value
     *
     * @mbg.generated
     */
    public void setJsonValue(String jsonValue) {
        this.jsonValue = jsonValue == null ? null : jsonValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_settings.key
     *
     * @return the value of admin_settings.key
     *
     * @mbg.generated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_settings.key
     *
     * @param key the value for admin_settings.key
     *
     * @mbg.generated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_settings
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AdminSettings other = (AdminSettings) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getJsonValue() == null ? other.getJsonValue() == null : this.getJsonValue().equals(other.getJsonValue()))
            && (this.getKey() == null ? other.getKey() == null : this.getKey().equals(other.getKey()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_settings
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getJsonValue() == null) ? 0 : getJsonValue().hashCode());
        result = prime * result + ((getKey() == null) ? 0 : getKey().hashCode());
        return result;
    }
}