package com.fnic.mybatis.thingsboard.model;

import java.util.ArrayList;
import java.util.List;

public class AlarmExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alarm
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alarm
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alarm
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alarm
     *
     * @mbg.generated
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alarm
     *
     * @mbg.generated
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    public AlarmExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table alarm
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAckTsIsNull() {
            addCriterion("ack_ts is null");
            return (Criteria) this;
        }

        public Criteria andAckTsIsNotNull() {
            addCriterion("ack_ts is not null");
            return (Criteria) this;
        }

        public Criteria andAckTsEqualTo(Long value) {
            addCriterion("ack_ts =", value, "ackTs");
            return (Criteria) this;
        }

        public Criteria andAckTsNotEqualTo(Long value) {
            addCriterion("ack_ts <>", value, "ackTs");
            return (Criteria) this;
        }

        public Criteria andAckTsGreaterThan(Long value) {
            addCriterion("ack_ts >", value, "ackTs");
            return (Criteria) this;
        }

        public Criteria andAckTsGreaterThanOrEqualTo(Long value) {
            addCriterion("ack_ts >=", value, "ackTs");
            return (Criteria) this;
        }

        public Criteria andAckTsLessThan(Long value) {
            addCriterion("ack_ts <", value, "ackTs");
            return (Criteria) this;
        }

        public Criteria andAckTsLessThanOrEqualTo(Long value) {
            addCriterion("ack_ts <=", value, "ackTs");
            return (Criteria) this;
        }

        public Criteria andAckTsIn(List<Long> values) {
            addCriterion("ack_ts in", values, "ackTs");
            return (Criteria) this;
        }

        public Criteria andAckTsNotIn(List<Long> values) {
            addCriterion("ack_ts not in", values, "ackTs");
            return (Criteria) this;
        }

        public Criteria andAckTsBetween(Long value1, Long value2) {
            addCriterion("ack_ts between", value1, value2, "ackTs");
            return (Criteria) this;
        }

        public Criteria andAckTsNotBetween(Long value1, Long value2) {
            addCriterion("ack_ts not between", value1, value2, "ackTs");
            return (Criteria) this;
        }

        public Criteria andClearTsIsNull() {
            addCriterion("clear_ts is null");
            return (Criteria) this;
        }

        public Criteria andClearTsIsNotNull() {
            addCriterion("clear_ts is not null");
            return (Criteria) this;
        }

        public Criteria andClearTsEqualTo(Long value) {
            addCriterion("clear_ts =", value, "clearTs");
            return (Criteria) this;
        }

        public Criteria andClearTsNotEqualTo(Long value) {
            addCriterion("clear_ts <>", value, "clearTs");
            return (Criteria) this;
        }

        public Criteria andClearTsGreaterThan(Long value) {
            addCriterion("clear_ts >", value, "clearTs");
            return (Criteria) this;
        }

        public Criteria andClearTsGreaterThanOrEqualTo(Long value) {
            addCriterion("clear_ts >=", value, "clearTs");
            return (Criteria) this;
        }

        public Criteria andClearTsLessThan(Long value) {
            addCriterion("clear_ts <", value, "clearTs");
            return (Criteria) this;
        }

        public Criteria andClearTsLessThanOrEqualTo(Long value) {
            addCriterion("clear_ts <=", value, "clearTs");
            return (Criteria) this;
        }

        public Criteria andClearTsIn(List<Long> values) {
            addCriterion("clear_ts in", values, "clearTs");
            return (Criteria) this;
        }

        public Criteria andClearTsNotIn(List<Long> values) {
            addCriterion("clear_ts not in", values, "clearTs");
            return (Criteria) this;
        }

        public Criteria andClearTsBetween(Long value1, Long value2) {
            addCriterion("clear_ts between", value1, value2, "clearTs");
            return (Criteria) this;
        }

        public Criteria andClearTsNotBetween(Long value1, Long value2) {
            addCriterion("clear_ts not between", value1, value2, "clearTs");
            return (Criteria) this;
        }

        public Criteria andAdditionalInfoIsNull() {
            addCriterion("additional_info is null");
            return (Criteria) this;
        }

        public Criteria andAdditionalInfoIsNotNull() {
            addCriterion("additional_info is not null");
            return (Criteria) this;
        }

        public Criteria andAdditionalInfoEqualTo(String value) {
            addCriterion("additional_info =", value, "additionalInfo");
            return (Criteria) this;
        }

        public Criteria andAdditionalInfoNotEqualTo(String value) {
            addCriterion("additional_info <>", value, "additionalInfo");
            return (Criteria) this;
        }

        public Criteria andAdditionalInfoGreaterThan(String value) {
            addCriterion("additional_info >", value, "additionalInfo");
            return (Criteria) this;
        }

        public Criteria andAdditionalInfoGreaterThanOrEqualTo(String value) {
            addCriterion("additional_info >=", value, "additionalInfo");
            return (Criteria) this;
        }

        public Criteria andAdditionalInfoLessThan(String value) {
            addCriterion("additional_info <", value, "additionalInfo");
            return (Criteria) this;
        }

        public Criteria andAdditionalInfoLessThanOrEqualTo(String value) {
            addCriterion("additional_info <=", value, "additionalInfo");
            return (Criteria) this;
        }

        public Criteria andAdditionalInfoLike(String value) {
            addCriterion("additional_info like", value, "additionalInfo");
            return (Criteria) this;
        }

        public Criteria andAdditionalInfoNotLike(String value) {
            addCriterion("additional_info not like", value, "additionalInfo");
            return (Criteria) this;
        }

        public Criteria andAdditionalInfoIn(List<String> values) {
            addCriterion("additional_info in", values, "additionalInfo");
            return (Criteria) this;
        }

        public Criteria andAdditionalInfoNotIn(List<String> values) {
            addCriterion("additional_info not in", values, "additionalInfo");
            return (Criteria) this;
        }

        public Criteria andAdditionalInfoBetween(String value1, String value2) {
            addCriterion("additional_info between", value1, value2, "additionalInfo");
            return (Criteria) this;
        }

        public Criteria andAdditionalInfoNotBetween(String value1, String value2) {
            addCriterion("additional_info not between", value1, value2, "additionalInfo");
            return (Criteria) this;
        }

        public Criteria andEndTsIsNull() {
            addCriterion("end_ts is null");
            return (Criteria) this;
        }

        public Criteria andEndTsIsNotNull() {
            addCriterion("end_ts is not null");
            return (Criteria) this;
        }

        public Criteria andEndTsEqualTo(Long value) {
            addCriterion("end_ts =", value, "endTs");
            return (Criteria) this;
        }

        public Criteria andEndTsNotEqualTo(Long value) {
            addCriterion("end_ts <>", value, "endTs");
            return (Criteria) this;
        }

        public Criteria andEndTsGreaterThan(Long value) {
            addCriterion("end_ts >", value, "endTs");
            return (Criteria) this;
        }

        public Criteria andEndTsGreaterThanOrEqualTo(Long value) {
            addCriterion("end_ts >=", value, "endTs");
            return (Criteria) this;
        }

        public Criteria andEndTsLessThan(Long value) {
            addCriterion("end_ts <", value, "endTs");
            return (Criteria) this;
        }

        public Criteria andEndTsLessThanOrEqualTo(Long value) {
            addCriterion("end_ts <=", value, "endTs");
            return (Criteria) this;
        }

        public Criteria andEndTsIn(List<Long> values) {
            addCriterion("end_ts in", values, "endTs");
            return (Criteria) this;
        }

        public Criteria andEndTsNotIn(List<Long> values) {
            addCriterion("end_ts not in", values, "endTs");
            return (Criteria) this;
        }

        public Criteria andEndTsBetween(Long value1, Long value2) {
            addCriterion("end_ts between", value1, value2, "endTs");
            return (Criteria) this;
        }

        public Criteria andEndTsNotBetween(Long value1, Long value2) {
            addCriterion("end_ts not between", value1, value2, "endTs");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdIsNull() {
            addCriterion("originator_id is null");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdIsNotNull() {
            addCriterion("originator_id is not null");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdEqualTo(String value) {
            addCriterion("originator_id =", value, "originatorId");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdNotEqualTo(String value) {
            addCriterion("originator_id <>", value, "originatorId");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdGreaterThan(String value) {
            addCriterion("originator_id >", value, "originatorId");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdGreaterThanOrEqualTo(String value) {
            addCriterion("originator_id >=", value, "originatorId");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdLessThan(String value) {
            addCriterion("originator_id <", value, "originatorId");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdLessThanOrEqualTo(String value) {
            addCriterion("originator_id <=", value, "originatorId");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdLike(String value) {
            addCriterion("originator_id like", value, "originatorId");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdNotLike(String value) {
            addCriterion("originator_id not like", value, "originatorId");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdIn(List<String> values) {
            addCriterion("originator_id in", values, "originatorId");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdNotIn(List<String> values) {
            addCriterion("originator_id not in", values, "originatorId");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdBetween(String value1, String value2) {
            addCriterion("originator_id between", value1, value2, "originatorId");
            return (Criteria) this;
        }

        public Criteria andOriginatorIdNotBetween(String value1, String value2) {
            addCriterion("originator_id not between", value1, value2, "originatorId");
            return (Criteria) this;
        }

        public Criteria andOriginatorTypeIsNull() {
            addCriterion("originator_type is null");
            return (Criteria) this;
        }

        public Criteria andOriginatorTypeIsNotNull() {
            addCriterion("originator_type is not null");
            return (Criteria) this;
        }

        public Criteria andOriginatorTypeEqualTo(Integer value) {
            addCriterion("originator_type =", value, "originatorType");
            return (Criteria) this;
        }

        public Criteria andOriginatorTypeNotEqualTo(Integer value) {
            addCriterion("originator_type <>", value, "originatorType");
            return (Criteria) this;
        }

        public Criteria andOriginatorTypeGreaterThan(Integer value) {
            addCriterion("originator_type >", value, "originatorType");
            return (Criteria) this;
        }

        public Criteria andOriginatorTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("originator_type >=", value, "originatorType");
            return (Criteria) this;
        }

        public Criteria andOriginatorTypeLessThan(Integer value) {
            addCriterion("originator_type <", value, "originatorType");
            return (Criteria) this;
        }

        public Criteria andOriginatorTypeLessThanOrEqualTo(Integer value) {
            addCriterion("originator_type <=", value, "originatorType");
            return (Criteria) this;
        }

        public Criteria andOriginatorTypeIn(List<Integer> values) {
            addCriterion("originator_type in", values, "originatorType");
            return (Criteria) this;
        }

        public Criteria andOriginatorTypeNotIn(List<Integer> values) {
            addCriterion("originator_type not in", values, "originatorType");
            return (Criteria) this;
        }

        public Criteria andOriginatorTypeBetween(Integer value1, Integer value2) {
            addCriterion("originator_type between", value1, value2, "originatorType");
            return (Criteria) this;
        }

        public Criteria andOriginatorTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("originator_type not between", value1, value2, "originatorType");
            return (Criteria) this;
        }

        public Criteria andPropagateIsNull() {
            addCriterion("propagate is null");
            return (Criteria) this;
        }

        public Criteria andPropagateIsNotNull() {
            addCriterion("propagate is not null");
            return (Criteria) this;
        }

        public Criteria andPropagateEqualTo(Boolean value) {
            addCriterion("propagate =", value, "propagate");
            return (Criteria) this;
        }

        public Criteria andPropagateNotEqualTo(Boolean value) {
            addCriterion("propagate <>", value, "propagate");
            return (Criteria) this;
        }

        public Criteria andPropagateGreaterThan(Boolean value) {
            addCriterion("propagate >", value, "propagate");
            return (Criteria) this;
        }

        public Criteria andPropagateGreaterThanOrEqualTo(Boolean value) {
            addCriterion("propagate >=", value, "propagate");
            return (Criteria) this;
        }

        public Criteria andPropagateLessThan(Boolean value) {
            addCriterion("propagate <", value, "propagate");
            return (Criteria) this;
        }

        public Criteria andPropagateLessThanOrEqualTo(Boolean value) {
            addCriterion("propagate <=", value, "propagate");
            return (Criteria) this;
        }

        public Criteria andPropagateIn(List<Boolean> values) {
            addCriterion("propagate in", values, "propagate");
            return (Criteria) this;
        }

        public Criteria andPropagateNotIn(List<Boolean> values) {
            addCriterion("propagate not in", values, "propagate");
            return (Criteria) this;
        }

        public Criteria andPropagateBetween(Boolean value1, Boolean value2) {
            addCriterion("propagate between", value1, value2, "propagate");
            return (Criteria) this;
        }

        public Criteria andPropagateNotBetween(Boolean value1, Boolean value2) {
            addCriterion("propagate not between", value1, value2, "propagate");
            return (Criteria) this;
        }

        public Criteria andSeverityIsNull() {
            addCriterion("severity is null");
            return (Criteria) this;
        }

        public Criteria andSeverityIsNotNull() {
            addCriterion("severity is not null");
            return (Criteria) this;
        }

        public Criteria andSeverityEqualTo(String value) {
            addCriterion("severity =", value, "severity");
            return (Criteria) this;
        }

        public Criteria andSeverityNotEqualTo(String value) {
            addCriterion("severity <>", value, "severity");
            return (Criteria) this;
        }

        public Criteria andSeverityGreaterThan(String value) {
            addCriterion("severity >", value, "severity");
            return (Criteria) this;
        }

        public Criteria andSeverityGreaterThanOrEqualTo(String value) {
            addCriterion("severity >=", value, "severity");
            return (Criteria) this;
        }

        public Criteria andSeverityLessThan(String value) {
            addCriterion("severity <", value, "severity");
            return (Criteria) this;
        }

        public Criteria andSeverityLessThanOrEqualTo(String value) {
            addCriterion("severity <=", value, "severity");
            return (Criteria) this;
        }

        public Criteria andSeverityLike(String value) {
            addCriterion("severity like", value, "severity");
            return (Criteria) this;
        }

        public Criteria andSeverityNotLike(String value) {
            addCriterion("severity not like", value, "severity");
            return (Criteria) this;
        }

        public Criteria andSeverityIn(List<String> values) {
            addCriterion("severity in", values, "severity");
            return (Criteria) this;
        }

        public Criteria andSeverityNotIn(List<String> values) {
            addCriterion("severity not in", values, "severity");
            return (Criteria) this;
        }

        public Criteria andSeverityBetween(String value1, String value2) {
            addCriterion("severity between", value1, value2, "severity");
            return (Criteria) this;
        }

        public Criteria andSeverityNotBetween(String value1, String value2) {
            addCriterion("severity not between", value1, value2, "severity");
            return (Criteria) this;
        }

        public Criteria andStartTsIsNull() {
            addCriterion("start_ts is null");
            return (Criteria) this;
        }

        public Criteria andStartTsIsNotNull() {
            addCriterion("start_ts is not null");
            return (Criteria) this;
        }

        public Criteria andStartTsEqualTo(Long value) {
            addCriterion("start_ts =", value, "startTs");
            return (Criteria) this;
        }

        public Criteria andStartTsNotEqualTo(Long value) {
            addCriterion("start_ts <>", value, "startTs");
            return (Criteria) this;
        }

        public Criteria andStartTsGreaterThan(Long value) {
            addCriterion("start_ts >", value, "startTs");
            return (Criteria) this;
        }

        public Criteria andStartTsGreaterThanOrEqualTo(Long value) {
            addCriterion("start_ts >=", value, "startTs");
            return (Criteria) this;
        }

        public Criteria andStartTsLessThan(Long value) {
            addCriterion("start_ts <", value, "startTs");
            return (Criteria) this;
        }

        public Criteria andStartTsLessThanOrEqualTo(Long value) {
            addCriterion("start_ts <=", value, "startTs");
            return (Criteria) this;
        }

        public Criteria andStartTsIn(List<Long> values) {
            addCriterion("start_ts in", values, "startTs");
            return (Criteria) this;
        }

        public Criteria andStartTsNotIn(List<Long> values) {
            addCriterion("start_ts not in", values, "startTs");
            return (Criteria) this;
        }

        public Criteria andStartTsBetween(Long value1, Long value2) {
            addCriterion("start_ts between", value1, value2, "startTs");
            return (Criteria) this;
        }

        public Criteria andStartTsNotBetween(Long value1, Long value2) {
            addCriterion("start_ts not between", value1, value2, "startTs");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNull() {
            addCriterion("tenant_id is null");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNotNull() {
            addCriterion("tenant_id is not null");
            return (Criteria) this;
        }

        public Criteria andTenantIdEqualTo(String value) {
            addCriterion("tenant_id =", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotEqualTo(String value) {
            addCriterion("tenant_id <>", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThan(String value) {
            addCriterion("tenant_id >", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThanOrEqualTo(String value) {
            addCriterion("tenant_id >=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThan(String value) {
            addCriterion("tenant_id <", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThanOrEqualTo(String value) {
            addCriterion("tenant_id <=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLike(String value) {
            addCriterion("tenant_id like", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotLike(String value) {
            addCriterion("tenant_id not like", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdIn(List<String> values) {
            addCriterion("tenant_id in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotIn(List<String> values) {
            addCriterion("tenant_id not in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdBetween(String value1, String value2) {
            addCriterion("tenant_id between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotBetween(String value1, String value2) {
            addCriterion("tenant_id not between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table alarm
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table alarm
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}