package com.fnic.mybatis.thingsboard.model;

public class AttributeKv {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute_kv.entity_type
     *
     * @mbg.generated
     */
    private String entityType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute_kv.entity_id
     *
     * @mbg.generated
     */
    private String entityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute_kv.attribute_type
     *
     * @mbg.generated
     */
    private String attributeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute_kv.attribute_key
     *
     * @mbg.generated
     */
    private String attributeKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute_kv.bool_v
     *
     * @mbg.generated
     */
    private Boolean boolV;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute_kv.str_v
     *
     * @mbg.generated
     */
    private String strV;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute_kv.long_v
     *
     * @mbg.generated
     */
    private Long longV;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute_kv.dbl_v
     *
     * @mbg.generated
     */
    private Double dblV;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute_kv.last_update_ts
     *
     * @mbg.generated
     */
    private Long lastUpdateTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute_kv.entity_type
     *
     * @return the value of attribute_kv.entity_type
     *
     * @mbg.generated
     */
    public String getEntityType() {
        return entityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute_kv.entity_type
     *
     * @param entityType the value for attribute_kv.entity_type
     *
     * @mbg.generated
     */
    public void setEntityType(String entityType) {
        this.entityType = entityType == null ? null : entityType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute_kv.entity_id
     *
     * @return the value of attribute_kv.entity_id
     *
     * @mbg.generated
     */
    public String getEntityId() {
        return entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute_kv.entity_id
     *
     * @param entityId the value for attribute_kv.entity_id
     *
     * @mbg.generated
     */
    public void setEntityId(String entityId) {
        this.entityId = entityId == null ? null : entityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute_kv.attribute_type
     *
     * @return the value of attribute_kv.attribute_type
     *
     * @mbg.generated
     */
    public String getAttributeType() {
        return attributeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute_kv.attribute_type
     *
     * @param attributeType the value for attribute_kv.attribute_type
     *
     * @mbg.generated
     */
    public void setAttributeType(String attributeType) {
        this.attributeType = attributeType == null ? null : attributeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute_kv.attribute_key
     *
     * @return the value of attribute_kv.attribute_key
     *
     * @mbg.generated
     */
    public String getAttributeKey() {
        return attributeKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute_kv.attribute_key
     *
     * @param attributeKey the value for attribute_kv.attribute_key
     *
     * @mbg.generated
     */
    public void setAttributeKey(String attributeKey) {
        this.attributeKey = attributeKey == null ? null : attributeKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute_kv.bool_v
     *
     * @return the value of attribute_kv.bool_v
     *
     * @mbg.generated
     */
    public Boolean getBoolV() {
        return boolV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute_kv.bool_v
     *
     * @param boolV the value for attribute_kv.bool_v
     *
     * @mbg.generated
     */
    public void setBoolV(Boolean boolV) {
        this.boolV = boolV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute_kv.str_v
     *
     * @return the value of attribute_kv.str_v
     *
     * @mbg.generated
     */
    public String getStrV() {
        return strV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute_kv.str_v
     *
     * @param strV the value for attribute_kv.str_v
     *
     * @mbg.generated
     */
    public void setStrV(String strV) {
        this.strV = strV == null ? null : strV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute_kv.long_v
     *
     * @return the value of attribute_kv.long_v
     *
     * @mbg.generated
     */
    public Long getLongV() {
        return longV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute_kv.long_v
     *
     * @param longV the value for attribute_kv.long_v
     *
     * @mbg.generated
     */
    public void setLongV(Long longV) {
        this.longV = longV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute_kv.dbl_v
     *
     * @return the value of attribute_kv.dbl_v
     *
     * @mbg.generated
     */
    public Double getDblV() {
        return dblV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute_kv.dbl_v
     *
     * @param dblV the value for attribute_kv.dbl_v
     *
     * @mbg.generated
     */
    public void setDblV(Double dblV) {
        this.dblV = dblV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute_kv.last_update_ts
     *
     * @return the value of attribute_kv.last_update_ts
     *
     * @mbg.generated
     */
    public Long getLastUpdateTs() {
        return lastUpdateTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute_kv.last_update_ts
     *
     * @param lastUpdateTs the value for attribute_kv.last_update_ts
     *
     * @mbg.generated
     */
    public void setLastUpdateTs(Long lastUpdateTs) {
        this.lastUpdateTs = lastUpdateTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_kv
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AttributeKv other = (AttributeKv) that;
        return (this.getEntityType() == null ? other.getEntityType() == null : this.getEntityType().equals(other.getEntityType()))
            && (this.getEntityId() == null ? other.getEntityId() == null : this.getEntityId().equals(other.getEntityId()))
            && (this.getAttributeType() == null ? other.getAttributeType() == null : this.getAttributeType().equals(other.getAttributeType()))
            && (this.getAttributeKey() == null ? other.getAttributeKey() == null : this.getAttributeKey().equals(other.getAttributeKey()))
            && (this.getBoolV() == null ? other.getBoolV() == null : this.getBoolV().equals(other.getBoolV()))
            && (this.getStrV() == null ? other.getStrV() == null : this.getStrV().equals(other.getStrV()))
            && (this.getLongV() == null ? other.getLongV() == null : this.getLongV().equals(other.getLongV()))
            && (this.getDblV() == null ? other.getDblV() == null : this.getDblV().equals(other.getDblV()))
            && (this.getLastUpdateTs() == null ? other.getLastUpdateTs() == null : this.getLastUpdateTs().equals(other.getLastUpdateTs()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_kv
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEntityType() == null) ? 0 : getEntityType().hashCode());
        result = prime * result + ((getEntityId() == null) ? 0 : getEntityId().hashCode());
        result = prime * result + ((getAttributeType() == null) ? 0 : getAttributeType().hashCode());
        result = prime * result + ((getAttributeKey() == null) ? 0 : getAttributeKey().hashCode());
        result = prime * result + ((getBoolV() == null) ? 0 : getBoolV().hashCode());
        result = prime * result + ((getStrV() == null) ? 0 : getStrV().hashCode());
        result = prime * result + ((getLongV() == null) ? 0 : getLongV().hashCode());
        result = prime * result + ((getDblV() == null) ? 0 : getDblV().hashCode());
        result = prime * result + ((getLastUpdateTs() == null) ? 0 : getLastUpdateTs().hashCode());
        return result;
    }
}