package com.fnic.mybatis.thingsboard.model;

public class ComponentDescriptor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column component_descriptor.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column component_descriptor.actions
     *
     * @mbg.generated
     */
    private String actions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column component_descriptor.clazz
     *
     * @mbg.generated
     */
    private String clazz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column component_descriptor.configuration_descriptor
     *
     * @mbg.generated
     */
    private String configurationDescriptor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column component_descriptor.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column component_descriptor.scope
     *
     * @mbg.generated
     */
    private String scope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column component_descriptor.search_text
     *
     * @mbg.generated
     */
    private String searchText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column component_descriptor.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column component_descriptor.id
     *
     * @return the value of component_descriptor.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column component_descriptor.id
     *
     * @param id the value for component_descriptor.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column component_descriptor.actions
     *
     * @return the value of component_descriptor.actions
     *
     * @mbg.generated
     */
    public String getActions() {
        return actions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column component_descriptor.actions
     *
     * @param actions the value for component_descriptor.actions
     *
     * @mbg.generated
     */
    public void setActions(String actions) {
        this.actions = actions == null ? null : actions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column component_descriptor.clazz
     *
     * @return the value of component_descriptor.clazz
     *
     * @mbg.generated
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column component_descriptor.clazz
     *
     * @param clazz the value for component_descriptor.clazz
     *
     * @mbg.generated
     */
    public void setClazz(String clazz) {
        this.clazz = clazz == null ? null : clazz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column component_descriptor.configuration_descriptor
     *
     * @return the value of component_descriptor.configuration_descriptor
     *
     * @mbg.generated
     */
    public String getConfigurationDescriptor() {
        return configurationDescriptor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column component_descriptor.configuration_descriptor
     *
     * @param configurationDescriptor the value for component_descriptor.configuration_descriptor
     *
     * @mbg.generated
     */
    public void setConfigurationDescriptor(String configurationDescriptor) {
        this.configurationDescriptor = configurationDescriptor == null ? null : configurationDescriptor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column component_descriptor.name
     *
     * @return the value of component_descriptor.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column component_descriptor.name
     *
     * @param name the value for component_descriptor.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column component_descriptor.scope
     *
     * @return the value of component_descriptor.scope
     *
     * @mbg.generated
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column component_descriptor.scope
     *
     * @param scope the value for component_descriptor.scope
     *
     * @mbg.generated
     */
    public void setScope(String scope) {
        this.scope = scope == null ? null : scope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column component_descriptor.search_text
     *
     * @return the value of component_descriptor.search_text
     *
     * @mbg.generated
     */
    public String getSearchText() {
        return searchText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column component_descriptor.search_text
     *
     * @param searchText the value for component_descriptor.search_text
     *
     * @mbg.generated
     */
    public void setSearchText(String searchText) {
        this.searchText = searchText == null ? null : searchText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column component_descriptor.type
     *
     * @return the value of component_descriptor.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column component_descriptor.type
     *
     * @param type the value for component_descriptor.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table component_descriptor
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ComponentDescriptor other = (ComponentDescriptor) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getActions() == null ? other.getActions() == null : this.getActions().equals(other.getActions()))
            && (this.getClazz() == null ? other.getClazz() == null : this.getClazz().equals(other.getClazz()))
            && (this.getConfigurationDescriptor() == null ? other.getConfigurationDescriptor() == null : this.getConfigurationDescriptor().equals(other.getConfigurationDescriptor()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getScope() == null ? other.getScope() == null : this.getScope().equals(other.getScope()))
            && (this.getSearchText() == null ? other.getSearchText() == null : this.getSearchText().equals(other.getSearchText()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table component_descriptor
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getActions() == null) ? 0 : getActions().hashCode());
        result = prime * result + ((getClazz() == null) ? 0 : getClazz().hashCode());
        result = prime * result + ((getConfigurationDescriptor() == null) ? 0 : getConfigurationDescriptor().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getScope() == null) ? 0 : getScope().hashCode());
        result = prime * result + ((getSearchText() == null) ? 0 : getSearchText().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        return result;
    }
}