package com.fnic.mybatis.thingsboard.model;

public class Plugin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.additional_info
     *
     * @mbg.generated
     */
    private String additionalInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.api_token
     *
     * @mbg.generated
     */
    private String apiToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.plugin_class
     *
     * @mbg.generated
     */
    private String pluginClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.configuration
     *
     * @mbg.generated
     */
    private String configuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.public_access
     *
     * @mbg.generated
     */
    private Boolean publicAccess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.search_text
     *
     * @mbg.generated
     */
    private String searchText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin.tenant_id
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.id
     *
     * @return the value of plugin.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.id
     *
     * @param id the value for plugin.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.additional_info
     *
     * @return the value of plugin.additional_info
     *
     * @mbg.generated
     */
    public String getAdditionalInfo() {
        return additionalInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.additional_info
     *
     * @param additionalInfo the value for plugin.additional_info
     *
     * @mbg.generated
     */
    public void setAdditionalInfo(String additionalInfo) {
        this.additionalInfo = additionalInfo == null ? null : additionalInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.api_token
     *
     * @return the value of plugin.api_token
     *
     * @mbg.generated
     */
    public String getApiToken() {
        return apiToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.api_token
     *
     * @param apiToken the value for plugin.api_token
     *
     * @mbg.generated
     */
    public void setApiToken(String apiToken) {
        this.apiToken = apiToken == null ? null : apiToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.plugin_class
     *
     * @return the value of plugin.plugin_class
     *
     * @mbg.generated
     */
    public String getPluginClass() {
        return pluginClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.plugin_class
     *
     * @param pluginClass the value for plugin.plugin_class
     *
     * @mbg.generated
     */
    public void setPluginClass(String pluginClass) {
        this.pluginClass = pluginClass == null ? null : pluginClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.configuration
     *
     * @return the value of plugin.configuration
     *
     * @mbg.generated
     */
    public String getConfiguration() {
        return configuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.configuration
     *
     * @param configuration the value for plugin.configuration
     *
     * @mbg.generated
     */
    public void setConfiguration(String configuration) {
        this.configuration = configuration == null ? null : configuration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.name
     *
     * @return the value of plugin.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.name
     *
     * @param name the value for plugin.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.public_access
     *
     * @return the value of plugin.public_access
     *
     * @mbg.generated
     */
    public Boolean getPublicAccess() {
        return publicAccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.public_access
     *
     * @param publicAccess the value for plugin.public_access
     *
     * @mbg.generated
     */
    public void setPublicAccess(Boolean publicAccess) {
        this.publicAccess = publicAccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.search_text
     *
     * @return the value of plugin.search_text
     *
     * @mbg.generated
     */
    public String getSearchText() {
        return searchText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.search_text
     *
     * @param searchText the value for plugin.search_text
     *
     * @mbg.generated
     */
    public void setSearchText(String searchText) {
        this.searchText = searchText == null ? null : searchText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.state
     *
     * @return the value of plugin.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.state
     *
     * @param state the value for plugin.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin.tenant_id
     *
     * @return the value of plugin.tenant_id
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin.tenant_id
     *
     * @param tenantId the value for plugin.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Plugin other = (Plugin) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAdditionalInfo() == null ? other.getAdditionalInfo() == null : this.getAdditionalInfo().equals(other.getAdditionalInfo()))
            && (this.getApiToken() == null ? other.getApiToken() == null : this.getApiToken().equals(other.getApiToken()))
            && (this.getPluginClass() == null ? other.getPluginClass() == null : this.getPluginClass().equals(other.getPluginClass()))
            && (this.getConfiguration() == null ? other.getConfiguration() == null : this.getConfiguration().equals(other.getConfiguration()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getPublicAccess() == null ? other.getPublicAccess() == null : this.getPublicAccess().equals(other.getPublicAccess()))
            && (this.getSearchText() == null ? other.getSearchText() == null : this.getSearchText().equals(other.getSearchText()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getTenantId() == null ? other.getTenantId() == null : this.getTenantId().equals(other.getTenantId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAdditionalInfo() == null) ? 0 : getAdditionalInfo().hashCode());
        result = prime * result + ((getApiToken() == null) ? 0 : getApiToken().hashCode());
        result = prime * result + ((getPluginClass() == null) ? 0 : getPluginClass().hashCode());
        result = prime * result + ((getConfiguration() == null) ? 0 : getConfiguration().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getPublicAccess() == null) ? 0 : getPublicAccess().hashCode());
        result = prime * result + ((getSearchText() == null) ? 0 : getSearchText().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getTenantId() == null) ? 0 : getTenantId().hashCode());
        return result;
    }
}