package com.fnic.mybatis.thingsboard.model;

public class Relation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.from_id
     *
     * @mbg.generated
     */
    private String fromId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.from_type
     *
     * @mbg.generated
     */
    private String fromType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.to_id
     *
     * @mbg.generated
     */
    private String toId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.to_type
     *
     * @mbg.generated
     */
    private String toType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.relation_type_group
     *
     * @mbg.generated
     */
    private String relationTypeGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.relation_type
     *
     * @mbg.generated
     */
    private String relationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.additional_info
     *
     * @mbg.generated
     */
    private String additionalInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation.from_id
     *
     * @return the value of relation.from_id
     *
     * @mbg.generated
     */
    public String getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation.from_id
     *
     * @param fromId the value for relation.from_id
     *
     * @mbg.generated
     */
    public void setFromId(String fromId) {
        this.fromId = fromId == null ? null : fromId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation.from_type
     *
     * @return the value of relation.from_type
     *
     * @mbg.generated
     */
    public String getFromType() {
        return fromType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation.from_type
     *
     * @param fromType the value for relation.from_type
     *
     * @mbg.generated
     */
    public void setFromType(String fromType) {
        this.fromType = fromType == null ? null : fromType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation.to_id
     *
     * @return the value of relation.to_id
     *
     * @mbg.generated
     */
    public String getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation.to_id
     *
     * @param toId the value for relation.to_id
     *
     * @mbg.generated
     */
    public void setToId(String toId) {
        this.toId = toId == null ? null : toId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation.to_type
     *
     * @return the value of relation.to_type
     *
     * @mbg.generated
     */
    public String getToType() {
        return toType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation.to_type
     *
     * @param toType the value for relation.to_type
     *
     * @mbg.generated
     */
    public void setToType(String toType) {
        this.toType = toType == null ? null : toType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation.relation_type_group
     *
     * @return the value of relation.relation_type_group
     *
     * @mbg.generated
     */
    public String getRelationTypeGroup() {
        return relationTypeGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation.relation_type_group
     *
     * @param relationTypeGroup the value for relation.relation_type_group
     *
     * @mbg.generated
     */
    public void setRelationTypeGroup(String relationTypeGroup) {
        this.relationTypeGroup = relationTypeGroup == null ? null : relationTypeGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation.relation_type
     *
     * @return the value of relation.relation_type
     *
     * @mbg.generated
     */
    public String getRelationType() {
        return relationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation.relation_type
     *
     * @param relationType the value for relation.relation_type
     *
     * @mbg.generated
     */
    public void setRelationType(String relationType) {
        this.relationType = relationType == null ? null : relationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relation.additional_info
     *
     * @return the value of relation.additional_info
     *
     * @mbg.generated
     */
    public String getAdditionalInfo() {
        return additionalInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relation.additional_info
     *
     * @param additionalInfo the value for relation.additional_info
     *
     * @mbg.generated
     */
    public void setAdditionalInfo(String additionalInfo) {
        this.additionalInfo = additionalInfo == null ? null : additionalInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Relation other = (Relation) that;
        return (this.getFromId() == null ? other.getFromId() == null : this.getFromId().equals(other.getFromId()))
            && (this.getFromType() == null ? other.getFromType() == null : this.getFromType().equals(other.getFromType()))
            && (this.getToId() == null ? other.getToId() == null : this.getToId().equals(other.getToId()))
            && (this.getToType() == null ? other.getToType() == null : this.getToType().equals(other.getToType()))
            && (this.getRelationTypeGroup() == null ? other.getRelationTypeGroup() == null : this.getRelationTypeGroup().equals(other.getRelationTypeGroup()))
            && (this.getRelationType() == null ? other.getRelationType() == null : this.getRelationType().equals(other.getRelationType()))
            && (this.getAdditionalInfo() == null ? other.getAdditionalInfo() == null : this.getAdditionalInfo().equals(other.getAdditionalInfo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFromId() == null) ? 0 : getFromId().hashCode());
        result = prime * result + ((getFromType() == null) ? 0 : getFromType().hashCode());
        result = prime * result + ((getToId() == null) ? 0 : getToId().hashCode());
        result = prime * result + ((getToType() == null) ? 0 : getToType().hashCode());
        result = prime * result + ((getRelationTypeGroup() == null) ? 0 : getRelationTypeGroup().hashCode());
        result = prime * result + ((getRelationType() == null) ? 0 : getRelationType().hashCode());
        result = prime * result + ((getAdditionalInfo() == null) ? 0 : getAdditionalInfo().hashCode());
        return result;
    }
}