package com.fnic.mybatis.thingsboard.model;

public class TsKv {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_kv.entity_type
     *
     * @mbg.generated
     */
    private String entityType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_kv.entity_id
     *
     * @mbg.generated
     */
    private String entityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_kv.key
     *
     * @mbg.generated
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_kv.ts
     *
     * @mbg.generated
     */
    private Long ts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_kv.bool_v
     *
     * @mbg.generated
     */
    private Boolean boolV;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_kv.str_v
     *
     * @mbg.generated
     */
    private String strV;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_kv.long_v
     *
     * @mbg.generated
     */
    private Long longV;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_kv.dbl_v
     *
     * @mbg.generated
     */
    private Double dblV;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_kv.entity_type
     *
     * @return the value of ts_kv.entity_type
     *
     * @mbg.generated
     */
    public String getEntityType() {
        return entityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_kv.entity_type
     *
     * @param entityType the value for ts_kv.entity_type
     *
     * @mbg.generated
     */
    public void setEntityType(String entityType) {
        this.entityType = entityType == null ? null : entityType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_kv.entity_id
     *
     * @return the value of ts_kv.entity_id
     *
     * @mbg.generated
     */
    public String getEntityId() {
        return entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_kv.entity_id
     *
     * @param entityId the value for ts_kv.entity_id
     *
     * @mbg.generated
     */
    public void setEntityId(String entityId) {
        this.entityId = entityId == null ? null : entityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_kv.key
     *
     * @return the value of ts_kv.key
     *
     * @mbg.generated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_kv.key
     *
     * @param key the value for ts_kv.key
     *
     * @mbg.generated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_kv.ts
     *
     * @return the value of ts_kv.ts
     *
     * @mbg.generated
     */
    public Long getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_kv.ts
     *
     * @param ts the value for ts_kv.ts
     *
     * @mbg.generated
     */
    public void setTs(Long ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_kv.bool_v
     *
     * @return the value of ts_kv.bool_v
     *
     * @mbg.generated
     */
    public Boolean getBoolV() {
        return boolV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_kv.bool_v
     *
     * @param boolV the value for ts_kv.bool_v
     *
     * @mbg.generated
     */
    public void setBoolV(Boolean boolV) {
        this.boolV = boolV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_kv.str_v
     *
     * @return the value of ts_kv.str_v
     *
     * @mbg.generated
     */
    public String getStrV() {
        return strV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_kv.str_v
     *
     * @param strV the value for ts_kv.str_v
     *
     * @mbg.generated
     */
    public void setStrV(String strV) {
        this.strV = strV == null ? null : strV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_kv.long_v
     *
     * @return the value of ts_kv.long_v
     *
     * @mbg.generated
     */
    public Long getLongV() {
        return longV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_kv.long_v
     *
     * @param longV the value for ts_kv.long_v
     *
     * @mbg.generated
     */
    public void setLongV(Long longV) {
        this.longV = longV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_kv.dbl_v
     *
     * @return the value of ts_kv.dbl_v
     *
     * @mbg.generated
     */
    public Double getDblV() {
        return dblV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_kv.dbl_v
     *
     * @param dblV the value for ts_kv.dbl_v
     *
     * @mbg.generated
     */
    public void setDblV(Double dblV) {
        this.dblV = dblV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_kv
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TsKv other = (TsKv) that;
        return (this.getEntityType() == null ? other.getEntityType() == null : this.getEntityType().equals(other.getEntityType()))
            && (this.getEntityId() == null ? other.getEntityId() == null : this.getEntityId().equals(other.getEntityId()))
            && (this.getKey() == null ? other.getKey() == null : this.getKey().equals(other.getKey()))
            && (this.getTs() == null ? other.getTs() == null : this.getTs().equals(other.getTs()))
            && (this.getBoolV() == null ? other.getBoolV() == null : this.getBoolV().equals(other.getBoolV()))
            && (this.getStrV() == null ? other.getStrV() == null : this.getStrV().equals(other.getStrV()))
            && (this.getLongV() == null ? other.getLongV() == null : this.getLongV().equals(other.getLongV()))
            && (this.getDblV() == null ? other.getDblV() == null : this.getDblV().equals(other.getDblV()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_kv
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEntityType() == null) ? 0 : getEntityType().hashCode());
        result = prime * result + ((getEntityId() == null) ? 0 : getEntityId().hashCode());
        result = prime * result + ((getKey() == null) ? 0 : getKey().hashCode());
        result = prime * result + ((getTs() == null) ? 0 : getTs().hashCode());
        result = prime * result + ((getBoolV() == null) ? 0 : getBoolV().hashCode());
        result = prime * result + ((getStrV() == null) ? 0 : getStrV().hashCode());
        result = prime * result + ((getLongV() == null) ? 0 : getLongV().hashCode());
        result = prime * result + ((getDblV() == null) ? 0 : getDblV().hashCode());
        return result;
    }
}